name: AWS CodeBuild CI
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  jdk8-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 7200
      - name: Run JDK8 build
        uses: aws-actions/aws-codebuild-run-build@v1
        timeout-minutes: 120
        with:
          project-name: aws-sdk-java-v2
  jdk11-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 7200
      - name: Run JDK11 build
        uses: aws-actions/aws-codebuild-run-build@v1
        timeout-minutes: 120
        with:
          project-name: aws-sdk-java-v2-JDK11
  jdk17-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 7200
      - name: Run JDK17 build
        uses: aws-actions/aws-codebuild-run-build@v1
        timeout-minutes: 120
        with:
          project-name: aws-sdk-java-v2-JDK17
  windows-jdk8-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 7200
      - name: Run JDK8 windows build
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: aws-sdk-java-v2-JDK8-windows
  native-image-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 7200
      - name: Run native image test
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: aws-sdk-java-v2-native-image-test
  sonar-cloud-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 7200
      - name: Run sonar-cloud analysis
        uses: aws-actions/aws-codebuild-run-build@v1
        timeout-minutes: 120
        with:
          project-name: aws-sdk-java-v2-sonar
          env-vars-for-codebuild: |
            PR,
            BRANCH,
            BASE
        env:
          PR: ${{ github.event.number }}
          BRANCH: ${{ github.head_ref || 'master'}}
          BASE: ${{ github.base_ref }}